# Generated by Django 5.2.17 on 2026-09-17 13:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Guest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournament_name", models.CharField(max_length=200)),
                (
                    "map",
                    models.CharField(
                        choices=[
                            ("Erangel", "Erangel"),
                            ("Miramar", "Miramar"),
                            ("Sanhok", "Sanhok"),
                            ("Livik", "Livik"),
                            ("Rondo", "Rondo"),
                            ("Vikendi", "Vikendi"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "game_mode",
                    models.CharField(
                        choices=[("Solo", "Solo"), ("Duo", "Duo"), ("Squad", "Squad")],
                        max_length=20,
                    ),
                ),
                ("tournament_date", models.DateField()),
                ("tournament_time", models.TimeField()),
                (
                    "entry_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "prize_pool",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "first_prize",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "second_prize",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "third_prize",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("matches", models.PositiveIntegerField(default=1)),
                ("total_slot", models.PositiveIntegerField(default=1)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="Guest.clanregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=200)),
                ("bgmi_id", models.CharField(max_length=100)),
                ("in_game_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("game_mode", models.CharField(max_length=50)),
                ("slot_number", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(default="Booked", max_length=50)),
                ("room_token", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "tournament_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="Guest.playerregistration",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="Clan.tournament",
                    ),
                ),
            ],
        ),
    ]
