# Generated by Django 5.2.17 on 2026-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClanRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clan_name", models.CharField(max_length=100)),
                ("clan_tag", models.CharField(max_length=6, unique=True)),
                ("captain_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=10)),
                (
                    "clan_type",
                    models.CharField(
                        choices=[
                            ("competitive", "Competitive"),
                            ("casual", "Casual"),
                            ("esports", "Esports"),
                        ],
                        max_length=20,
                    ),
                ),
                ("captain_bgmi_id", models.CharField(max_length=50, unique=True)),
                (
                    "game_mode",
                    models.CharField(
                        choices=[("duo", "Duo"), ("squad", "Squad")], max_length=10
                    ),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(
                        choices=[(2, "2 Members"), (3, "3 Members"), (4, "4 Members")]
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "clan_logo",
                    models.ImageField(blank=True, null=True, upload_to="clan_logos/"),
                ),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=10)),
                ("bgmi_id", models.CharField(max_length=50, unique=True)),
                ("in_game_name", models.CharField(max_length=100)),
                (
                    "game_mode",
                    models.CharField(
                        choices=[("solo", "Solo"), ("duo", "Duo"), ("squad", "Squad")],
                        max_length=10,
                    ),
                ),
                (
                    "player_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("assault", "Assault"),
                            ("sniper", "Sniper"),
                            ("support", "Support"),
                            ("igl", "IGL"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="player_profiles/"
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
