# Generated by Django 5.2.17 on 2026-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clanregistration",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
